# Generated by Django 2.0.2 on 2019-08-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Working', models.CharField(max_length=20)),
                ('Followups', models.TextField()),
            ],
        ),
    ]
