# Generated by Django 2.0.2 on 2019-08-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Working',
            new_name='Working_in',
        ),
    ]
