# Generated by Django 2.0.2 on 2019-09-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190828_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityName', models.CharField(max_length=20)),
                ('FromDate', models.CharField(max_length=10)),
                ('ToDate', models.CharField(max_length=10)),
                ('Venue', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=21)),
                ('District', models.CharField(max_length=40)),
                ('Village_Panchayat', models.CharField(max_length=40)),
                ('ActivityDescription', models.TextField()),
            ],
        ),
    ]
